force-app/main/default/objects/Park_Of_Interest__c/Park_Of_Interest__c.object-meta.xml
<CustomObject>
    <description>A junction object between Lead/Contact and an Adventure Park. Allows one person to be interested in many adventure parks.</description>
    <label>Park Of Interest</label>
    <nameField>
        <displayFormat>POI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parks Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Of_Interest__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/Park_Tour__c.object-meta.xml
<CustomObject>
    <description>A junction object between Leads/Contact and Adventure Parks. Represents an actual tour of a park, which differentiates itself from POIs. Parks of Interest represents merely interest and desired park adventure. But a Park Tour is an actual tour of the adventure.</description>
    <label>Park Tour</label>
    <nameField>
        <displayFormat>PT-{000}</displayFormat>
        <label>Park Tour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Park Tour</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Tour__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadDeletionHandler.cls
public with sharing class LeadDeletionHandler implements TriggerAction.BeforeDelete {

    public void beforeDelete(List<Lead> deletedLeads) {
        deleteRelatedPOIs(deletedLeads);
        deleteRelatedTours(deletedLeads);
    }

    //@test: should_delete_related_POIs_and_Park_Tours_on_lead_delete
    private static void deleteRelatedPOIs(List<Lead> deletedLeads) {
        List<Park_Of_Interest__c> relatedParksOfInterest = new List<Park_Of_Interest__c>([
            SELECT Id
            FROM Park_Of_Interest__c
            WHERE Lead__c IN :deletedLeads
        ]);

        if (!relatedParksOfInterest.isEmpty()) {
            delete relatedParksOfInterest;
        }
    }

    //@test: should_delete_related_POIs_and_Park_Tours_on_lead_delete
    private static void deleteRelatedTours(List<Lead> deletedLeads) {
        List<Park_Tour__c> relatedParkTours = new List<Park_Tour__c>([
            SELECT Id
            FROM Park_Tour__c
            WHERE Lead__c IN :deletedLeads
        ]);

        if (!relatedParkTours.isEmpty()) {
            delete relatedParkTours;
        }
    }
}