force-app/main/default/objects/Park_Tour__c/Park_Tour__c.object-meta.xml
<CustomObject>
    <description>A junction object between Leads/Contact and Adventure Parks. Represents an actual tour of a park, which differentiates itself from POIs. Parks of Interest represents merely interest and desired park adventure. But a Park Tour is an actual tour of the adventure.</description>
    <label>Park Tour</label>
    <nameField>
        <displayFormat>PT-{000}</displayFormat>
        <label>Park Tour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Park Tour</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Tour__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ParkTourTrigger_Handler.cls
public without sharing class ParkTourTrigger_Handler {

    //todo: this is the perfect use case for converting Apex to a Flow
    public static void onBeforeInsert(List<Park_Tour__c> newParkTours) {
        List<Id> leadIds = new List<Id>();
        List<Id> contactIds = new List<Id>();
        for (Park_Tour__c newTour : newParkTours) {
            if (String.isNotEmpty(newTour.Lead__c)) {
                leadIds.add(newTour.Lead__c);
            }

            if (String.isNotEmpty(newTour.Contact__c)) {
                contactIds.add(newTour.Contact__c);
            }
        }

        if (!leadIds.isEmpty()) {
            ParkTourTrigger_Helper.checkLeadForRepeatTour(newParkTours, leadIds);
        }

        if (!contactIds.isEmpty()) {
            ParkTourTrigger_Helper.checkContactForRepeatTour(newParkTours, contactIds);
        }
    }
}