force-app/main/default/objects/Account/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adventure_Park__c/Adventure_Park__c.object-meta.xml
<CustomObject>
    <description>Represents one park where adventure is to be had!</description>
    <label>Adventure Park</label>
    <nameField>
        <label>Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Parks_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Parks_Of_Interest__c</fullName>
    <description>Some technology in our enterprise stack can update Lead records directly. During this update, this field is used to temporarily store Park Numbers, which are then used by the automation to create POIs.</description>
    <label>Parks Of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Vendor_Segment_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Segment_Id__c</fullName>
    <description>The 3rd party partner Id where the lead originated from.</description>
    <label>Vendor Segment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Adventure_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Timeframe__c</fullName>
    <description>The general timeframe for going on an adventure.</description>
    <label>Adventure Timeframe</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Created_From_Lead__c.field-meta.xml
<CustomField>
    <fullName>Created_From_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Some field that is only checked when an Opportunity is created by Lead Conversion. But nobody knows why.</description>
    <label>Created From Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Household_Income__c.field-meta.xml
<CustomField>
    <fullName>Household_Income__c</fullName>
    <description>The general range of income for the lead.</description>
    <label>Household Income</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_Segment_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Segment_Id__c</fullName>
    <description>The 3rd party partner Id where the lead originated from.</description>
    <label>Vendor Segment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/Park_Of_Interest__c.object-meta.xml
<CustomObject>
    <description>A junction object between Lead/Contact and an Adventure Park. Allows one person to be interested in many adventure parks.</description>
    <label>Park Of Interest</label>
    <nameField>
        <displayFormat>POI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parks Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Of_Interest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/Park_Tour__c.object-meta.xml
<CustomObject>
    <description>A junction object between Leads/Contact and Adventure Parks. Represents an actual tour of a park, which differentiates itself from POIs. Parks of Interest represents merely interest and desired park adventure. But a Park Tour is an actual tour of the adventure.</description>
    <label>Park Tour</label>
    <nameField>
        <displayFormat>PT-{000}</displayFormat>
        <label>Park Tour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Park Tour</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Tour__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadConversionDataMapper.cls
public with sharing class LeadConversionDataMapper implements TriggerAction.AfterUpdate {

    public void afterUpdate(List<Lead> newLeads, List<Lead> oldLeads) {
        Set<Id> convertedLeadIds = new Set<Id>();
        for (Integer i = 0; i < newLeads.size(); i++) {
            Lead newLead = newLeads[i];
            Lead oldLead = oldLeads[i];
            if (newLead.IsConverted && !oldLead.IsConverted) {
                convertedLeadIds.add(newLead.Id);
            }
        }

        if (!convertedLeadIds.isEmpty()) {
            remapDataForConvertedLeads(convertedLeadIds);
        }
    }

    //@test: should_map_data_from_Converted_Lead_to_related_records
    public static void remapDataForConvertedLeads(Set<Id> convertedLeadIds) {

        List<Account> updatedAccounts = new List<Account>();
        List<Opportunity> updatedOpportunities = new List<Opportunity>();
        List<Park_Tour__c> toursForUpdate = new List<Park_Tour__c>();
        List<Park_Of_Interest__c> poiForUpdate = new List<Park_Of_Interest__c>();
        for (Lead lead : [
            SELECT Id, ConvertedAccountId, ConvertedContactId, ConvertedOpportunityId, Vendor_Segment_Id__c,
                LastName, Phone, MobilePhone, Email, Adventure_Timeframe__c, Household_Income__c,
            (SELECT Id, Lead__c, Adventure_Park__c FROM Park_Tour__r WHERE Lead__c IN :convertedLeadIds ORDER BY Id),
            (SELECT Id, Lead__c FROM Parks_Of_Interest__r WHERE Lead__c IN :convertedLeadIds)
            FROM Lead
            WHERE Id IN :convertedLeadIds
        ]) {

            Id accountIdFromConversion = lead.ConvertedAccountId;
            if (accountIdFromConversion != null) {
                Account updatedAccount = updateAccountContactInfo(lead);
                updatedAccounts.add(updatedAccount);
            }

            Id opportunityFromConversion = lead.ConvertedOpportunityId;
            if (opportunityFromConversion != null) {
                Opportunity updatedOpportunity = mapOpportunityFromConvertedLead(lead);

                if (!updatedOpportunities.contains(updatedOpportunity)) {
                    updatedOpportunities.add(updatedOpportunity);
                }
            }

            toursForUpdate.addAll(mapParkToursFromConvertedLead(lead));
            poiForUpdate.addAll(mapPOIsFromConvertedLead(lead));
        }

        if (!updatedAccounts.isEmpty()) {
            update updatedAccounts;
        }

        if (!updatedOpportunities.isEmpty()) {
            update updatedOpportunities;
        }

        if (!toursForUpdate.isEmpty()) {
            update toursForUpdate;
        }

        if (!poiForUpdate.isEmpty()) {
            update poiForUpdate;
        }

        List<OpportunityContactRole> updatedOCRs = mapOCRs(updatedOpportunities);
        if (!updatedOCRs.isEmpty()) {
            update updatedOCRs;
        }
    }

    private static Account updateAccountContactInfo(Lead convertedLead) {
        return new Account(
            Id = convertedLead.ConvertedAccountId,
            Phone = convertedLead.Phone,
            Email__c = convertedLead.Email
        );
    }

    private static Opportunity mapOpportunityFromConvertedLead(Lead convertedLead) {
        return new Opportunity(
            Id = convertedLead.ConvertedOpportunityId,
            Adventure_Timeframe__c = convertedLead.Adventure_Timeframe__c,
            Household_Income__c = convertedLead.Household_Income__c,
            Vendor_Segment_Id__c = convertedLead.Vendor_Segment_Id__c,
            Created_From_Lead__c = true
        );
    }

    private static List<Park_Tour__c> mapParkToursFromConvertedLead(Lead convertedLead) {
        List<Park_Tour__c> remappedTours = new List<Park_Tour__c>();
        for (Park_Tour__c tour : convertedLead.Park_Tour__r) {
            tour.Lead__c = null;
            tour.Contact__c = convertedLead.ConvertedContactId;
            tour.Opportunity__c = convertedLead.ConvertedOpportunityId;
            remappedTours.add(tour);
        }
        return remappedTours;
    }

    private static List<Park_Of_Interest__c> mapPOIsFromConvertedLead(Lead convertedLead) {
        List<Park_Of_Interest__c> remappedPOIs = new List<Park_Of_Interest__c>();
        for (Park_Of_Interest__c poi : convertedLead.Parks_Of_Interest__r) {
            poi.Lead__c = null;
            poi.Contact__c = convertedLead.ConvertedContactId;
            remappedPOIs.add(poi);
        }
        return remappedPOIs;
    }

    private static List<OpportunityContactRole> mapOCRs(List<Opportunity> opportunities) {
        List<OpportunityContactRole> mappedOCRs = new List<OpportunityContactRole>();
        for (OpportunityContactRole ocr : [
            SELECT Id, OpportunityId
            FROM OpportunityContactRole
            WHERE OpportunityId IN :opportunities
        ]) {
            ocr.Role = 'Buyer';
            ocr.IsPrimary = true;
            mappedOCRs.add(ocr);
        }
        return mappedOCRs;
    }
}