force-app/main/default/objects/Account/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adventure_Park__c/Adventure_Park__c.object-meta.xml
<CustomObject>
    <description>Represents one park where adventure is to be had!</description>
    <label>Adventure Park</label>
    <nameField>
        <label>Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure_Park__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Adventure_Park__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <description>The date the park will be or was opened to adventurers.</description>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Adventure_Park__c/fields/Park_Number__c.field-meta.xml
<CustomField>
    <fullName>Park_Number__c</fullName>
    <description>The unique, 12 digit number assigned to a park.</description>
    <label>Park Number</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Accept_Lead__c.field-meta.xml
<CustomField>
    <fullName>Accept_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>No one know what this field is for, if it is used, or when it was used last.</description>
    <label>Accept Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Committed__c.field-meta.xml
<CustomField>
    <fullName>Committed__c</fullName>
    <description>The date the Lead commits to an adventure, which converts the Lead to an Opportunity.</description>
    <label>Committed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Disinterested_Reason__c.field-meta.xml
<CustomField>
    <fullName>Disinterested_Reason__c</fullName>
    <description>When the lead is no longer interested, a reason is required. This is used to help with future marketing effort.</description>
    <label>Disinterested Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Parks_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Parks_Of_Interest__c</fullName>
    <description>Some technology in our enterprise stack can update Lead records directly. During this update, this field is used to temporarily store Park Numbers, which are then used by the automation to create POIs.</description>
    <label>Parks Of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Reprocessed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reprocessed_Reason__c</fullName>
    <description>Lead can be reprocessed manually, but they require a reason. When the automation reprocesses them, the reason is provided by the automation.</description>
    <label>Reprocessed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Vendor_Segment_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Segment_Id__c</fullName>
    <description>The 3rd party partner Id where the lead originated from.</description>
    <label>Vendor Segment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Adventure_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Timeframe__c</fullName>
    <description>The general timeframe for going on an adventure.</description>
    <label>Adventure Timeframe</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Created_From_Lead__c.field-meta.xml
<CustomField>
    <fullName>Created_From_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Some field that is only checked when an Opportunity is created by Lead Conversion. But nobody knows why.</description>
    <label>Created From Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Household_Income__c.field-meta.xml
<CustomField>
    <fullName>Household_Income__c</fullName>
    <description>The general range of income for the lead.</description>
    <label>Household Income</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_Segment_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Segment_Id__c</fullName>
    <description>The 3rd party partner Id where the lead originated from.</description>
    <label>Vendor Segment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/Park_Of_Interest__c.object-meta.xml
<CustomObject>
    <description>A junction object between Lead/Contact and an Adventure Park. Allows one person to be interested in many adventure parks.</description>
    <label>Park Of Interest</label>
    <nameField>
        <displayFormat>POI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parks Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Of_Interest__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/Park_Tour__c.object-meta.xml
<CustomObject>
    <description>A junction object between Leads/Contact and Adventure Parks. Represents an actual tour of a park, which differentiates itself from POIs. Parks of Interest represents merely interest and desired park adventure. But a Park Tour is an actual tour of the adventure.</description>
    <label>Park Tour</label>
    <nameField>
        <displayFormat>PT-{000}</displayFormat>
        <label>Park Tour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Park Tour</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Tour__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTrigger_Test.cls
@IsTest
private class LeadTrigger_Test {

    @IsTest
    static void reprocessed_lead_should_be_assigned_to_Marketing_User_on_Insert() {
        Lead lead = creatLead();

        Test.startTest();
        lead.Status = 'Reprocessed';
        insert lead;
        Test.stopTest();

        Lead updatedLead = [SELECT Owner.Id FROM Lead WHERE Id = :lead.Id];
        Assert.isNotNull(updatedLead.OwnerId);
    }

    @IsTest
    static void reprocessed_lead_should_be_assigned_to_Marketing_User_on_Update() {
        Lead lead = creatLead();
        insert lead;

        Test.startTest();
        lead.Status = 'Reprocessed';
        update lead;
        Test.stopTest();

        Lead updatedLead = [SELECT Owner.Id FROM Lead WHERE Id = :lead.Id];
        Assert.isNotNull(updatedLead.OwnerId);
    }

    @IsTest
    static void should_capture_status_change_date() {
        Lead lead = new Lead(
                FirstName = 'Lhorie',
                LastName = 'Salvadory',
                Email = 'lhorie@launch.com',
                Company = 'Launch with Lhorie'
        );
        insert lead;

        Test.startTest();
        lead.Status = 'Committed';
        update lead;
        Test.stopTest();

        Lead updatedLead = [SELECT Committed__c FROM Lead WHERE Id = :lead.Id];
        Assert.areEqual(Date.today(), updatedLead.Committed__c);
    }

    @IsTest
    static void should_create_POI_and_nullify_Lead() {
        Adventure_Park__c park = createPark();
        insert park;

        Lead lead = creatLead();
        lead.Parks_Of_Interest__c = park.Id;

        Test.startTest();
        insert lead;
        Test.stopTest();

        List<Park_Of_Interest__c> poiList = [SELECT Id FROM Park_Of_Interest__c WHERE Adventure_Park__c = :park.Id];
        Assert.areEqual(1, poiList.size());

        Lead updatedLead = [SELECT Parks_Of_Interest__c FROM Lead WHERE Id = :lead.Id LIMIT 1];
        Assert.isNull(updatedLead.Parks_Of_Interest__c);
    }

    @IsTest
    static void should_reassign_accepted_lead_on_update() {
        Lead lead = creatLead();
        insert lead;

        User someoneElse = getAnotherUser();

        System.runAs(someoneElse) {
            Test.startTest();
            lead.Accept_Lead__c = true;
            update lead;
            Test.stopTest();
        }

        Lead newLead = [SELECT OwnerId FROM Lead WHERE Id = :lead.Id];
        Assert.areEqual(someoneElse.Id, newLead.OwnerId);
    }

    @IsTest
    static void should_set_status_to_Disinterested() {
        Lead lead = creatLead();
        insert lead;

        Test.startTest();
        lead.Disinterested_Reason__c = 'Does not like the climate';
        update lead;
        Test.stopTest();

        Lead updatedLead = [SELECT Disinterested_Reason__c, Status FROM Lead WHERE Id = :lead.Id LIMIT 1];
        Assert.areEqual('Disinterested', updatedLead.Status);
    }

    @IsTest
    static void should_set_status_to_Engaged() {
        Lead lead = creatLead();
        insert lead;

        Test.startTest();
        lead.Reprocessed_Reason__c = 'Different park theme';
        update lead;
        Test.stopTest();

        Lead updatedLead = [SELECT Status FROM Lead WHERE Id = :lead.Id LIMIT 1];
        Assert.areEqual('Engaged', updatedLead.Status);
    }

    @IsTest
    static void should_set_status_to_Reprocessed_and_reassign_to_Marketing_User() {
        Lead lead = creatLead();
        insert lead;

        Test.startTest();
        lead.Reprocessed_Reason__c = 'Lead went stale';
        update lead;
        Test.stopTest();

        Lead updatedLead = [SELECT Status, OwnerId FROM Lead WHERE Id = :lead.Id LIMIT 1];
        Assert.areEqual('Reprocessed', updatedLead.Status);

    }

    @IsTest
    static void should_map_data_from_Converted_Lead_to_related_records() {
        Adventure_Park__c firstPark = createPark();
        Adventure_Park__c secondPark = createPark();
        secondPark.Name = 'Another Park';
        secondPark.Park_Number__c = '000999111222';
        insert firstPark;
        insert secondPark;

        Lead lead = creatLead();
        lead.Email = 'original@email.com';
        lead.Phone = '555-555-1234';
        lead.Adventure_Timeframe__c = '6 months';
        lead.Household_Income__c = '250000';
        lead.Vendor_Segment_Id__c = '123456';
        insert lead;

        Park_Tour__c firstTour = createParkTour(firstPark, lead);
        Park_Tour__c secondTour = createParkTour(secondPark, lead);
        insert firstTour;
        insert secondTour;

        Park_Of_Interest__c firstPOI = createPOI(firstPark, lead);
        Park_Of_Interest__c secondPOI = createPOI(secondPark, lead);
        insert firstPOI;
        insert secondPOI;

        Test.startTest();
        LeadStatus convertStatus = [SELECT ApiName FROM LeadStatus WHERE IsConverted = TRUE LIMIT 1];
        Database.LeadConvert convert = new Database.LeadConvert();
        convert.setLeadId(lead.Id);
        convert.setConvertedStatus(convertStatus.ApiName);
        Database.LeadConvertResult convertResult = Database.convertLead(convert, true);
        Test.stopTest();

        Assert.isTrue(convertResult.isSuccess());

        List<Account> updatedAccounts = [SELECT Phone FROM Account WHERE Email__c = :lead.Email];
        Assert.areEqual(1, updatedAccounts.size());
        Assert.areEqual(lead.Phone, updatedAccounts[0].Phone);

        List<Opportunity> updatedOpportunities = [
                SELECT Adventure_Timeframe__c, Household_Income__c, Vendor_Segment_Id__c
                FROM Opportunity
                WHERE Created_From_Lead__c = TRUE
                LIMIT 1
        ];
        Assert.areEqual(1, updatedOpportunities.size());
        Assert.areEqual(lead.Adventure_Timeframe__c, updatedOpportunities[0].Adventure_Timeframe__c);
        Assert.areEqual(lead.Household_Income__c, updatedOpportunities[0].Household_Income__c);
        Assert.areEqual(lead.Vendor_Segment_Id__c, updatedOpportunities[0].Vendor_Segment_Id__c);

        List<Park_Tour__c> parkTours = [SELECT Lead__c, Opportunity__c, Contact__c FROM Park_Tour__c];
        Assert.areEqual(2, parkTours.size());
        for (Park_Tour__c tour : parkTours) {
            Assert.isNull(tour.Lead__c);
            Assert.isNotNull(tour.Opportunity__c);
            Assert.isNotNull(tour.Contact__c);
        }

        List<Park_Of_Interest__c> parksOfInterest = [SELECT Lead__c, Contact__c FROM Park_Of_Interest__c];
        Assert.areEqual(2, parksOfInterest.size());
        for (Park_Of_Interest__c poi : parksOfInterest) {
            Assert.isNull(poi.Lead__c);
            Assert.isNotNull(poi.Contact__c);
        }

        List<OpportunityContactRole> ocrRecords = [SELECT Role, IsPrimary FROM OpportunityContactRole];
        Assert.areEqual(1, ocrRecords.size());
        Assert.areEqual('Buyer', ocrRecords[0].Role);
        Assert.isTrue(ocrRecords[0].IsPrimary);
    }

    @IsTest
    static void should_create_POI_for_existing_lead() {
        Adventure_Park__c onePark = createPark();
        insert onePark;

        Lead lead = creatLead();
        lead.Parks_Of_Interest__c = onePark.Id;
        insert lead;

        Adventure_Park__c anotherPark = createPark();
        anotherPark.Park_Number__c = '919818717616';
        insert anotherPark;

        Test.startTest();
        lead.Parks_Of_Interest__c = anotherPark.Id;
        update lead;
        Test.stopTest();

        List<Park_Of_Interest__c> parksOfInterest = [SELECT Lead__c FROM Park_Of_Interest__c];
        Assert.areEqual(2, parksOfInterest.size());
        for (Park_Of_Interest__c poi : parksOfInterest) {
            Assert.areEqual(lead.Id, poi.Lead__c);
        }

        Lead updatedLead = [SELECT Parks_Of_Interest__c FROM Lead];
        Assert.isNull(updatedLead.Parks_Of_Interest__c);
    }

    @IsTest
    static void should_delete_related_POIs_on_lead_delete() {
        Adventure_Park__c park = createPark();
        insert park;

        Lead lead = creatLead();
        lead.Parks_Of_Interest__c = park.Id;
        insert lead;

        List<Park_Of_Interest__c> parksOfInterest = [SELECT Id FROM Park_Of_Interest__c];
        Assert.areEqual(1, parksOfInterest.size());

        Test.startTest();
        delete lead;
        Test.stopTest();

        parksOfInterest = [SELECT Id FROM Park_Of_Interest__c];
        Assert.areEqual(0, parksOfInterest.size());
    }

    /** @return TEST DATA AND SETUP *****/

    static Adventure_Park__c createPark() {
        return new Adventure_Park__c(
                Name = 'Test Park',
                Park_Number__c = '123412341234',
                Is_Active__c = true,
                Open_Date__c = Date.today()
        );
    }

    static Lead creatLead() {
        return new Lead(
                FirstName = 'Lhorie',
                LastName = 'Salvadory',
                Email = 'lhorie@launch.com',
                Company = 'Launch with Lhorie'
        );
    }

    static Park_Tour__c createParkTour(Adventure_Park__c park, Lead lead) {
        return new Park_Tour__c(
                Adventure_Park__c = park.Id,
                Lead__c = lead.Id
        );
    }

    static Park_Of_Interest__c createPOI(Adventure_Park__c park, Lead lead) {
        return new Park_Of_Interest__c(
                Adventure_Park__c = park.Id,
                Lead__c = lead.Id
        );
    }

    private static User getAnotherUser() {
        User someoneElse = [SELECT Id FROM User WHERE IsActive = TRUE AND Id != :UserInfo.getUserId() LIMIT 1];
        return someoneElse;
    }

    @TestSetup
    static void setup() {
        Pricebook2 standardPricebook = new Pricebook2(
                Id = Test.getStandardPricebookId(),
                IsActive = true
        );
        update standardPricebook;
    }
}