force-app/main/default/objects/Adventure_Park__c/Adventure_Park__c.object-meta.xml
<CustomObject>
    <description>Represents one park where adventure is to be had!</description>
    <label>Adventure Park</label>
    <nameField>
        <label>Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure_Park__c/fields/Inactivated_Date__c.field-meta.xml
<CustomField>
    <fullName>Inactivated_Date__c</fullName>
    <description>The day this park was inactivated.</description>
    <label>Inactivated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/Park_Of_Interest__c.object-meta.xml
<CustomObject>
    <description>A junction object between Lead/Contact and an Adventure Park. Allows one person to be interested in many adventure parks.</description>
    <label>Park Of Interest</label>
    <nameField>
        <displayFormat>POI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parks Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Of_Interest__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Inactivated_Date__c.field-meta.xml
<CustomField>
    <fullName>Inactivated_Date__c</fullName>
    <description>Most wonder why this field is here and on the park. Some say it is to make it easy to find records that were deactivated by automation, in case deactivating the Park was a user error.</description>
    <label>Inactivated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AdventureParkTrigger_Helper.cls
public with sharing class AdventureParkTrigger_Helper {

    //@test: should_set_Inactivated_Date_and_deactivate_related_POIs()
    public static void deactivateRelatedParksOfInterest(Map<Id, Date> deactivatedDateByParkId) {
        List<Park_Of_Interest__c> parkOfInterests = new List<Park_Of_Interest__c>();
        for (Park_Of_Interest__c parkOfInterest: [
                SELECT Inactive__c, Adventure_Park__c
                FROM Park_Of_Interest__c
                WHERE Adventure_Park__c IN :deactivatedDateByParkId.keySet()
        ]) {
            parkOfInterest.Inactive__c = true;
            parkOfInterest.Inactivated_Date__c = deactivatedDateByParkId.get(parkOfInterest.Adventure_Park__c);
            parkOfInterests.add(parkOfInterest);
        }
        update parkOfInterests;
    }
}