force-app/main/default/objects/Adventure_Park__c/Adventure_Park__c.object-meta.xml
<CustomObject>
    <description>Represents one park where adventure is to be had!</description>
    <label>Adventure Park</label>
    <nameField>
        <label>Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Park_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Park_Of_Interest__c</fullName>
    <description>A temp field to write a POI Id to, which will be used to create a POI if not already existing.</description>
    <label>Park Of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/Park_Of_Interest__c.object-meta.xml
<CustomObject>
    <description>A junction object between Lead/Contact and an Adventure Park. Allows one person to be interested in many adventure parks.</description>
    <label>Park Of Interest</label>
    <nameField>
        <displayFormat>POI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parks Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Of_Interest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ParkOfInterestTrigger_Handler.cls
public with sharing class ParkOfInterestTrigger_Handler {
    public static Boolean avoidInsertRecursion = false;
    public static Boolean avoidDeleteRecursion = false;

    public static void onBeforeInsert(List<Park_Of_Interest__c> newPOIs) {
        Map<Id, Park_Of_Interest__c> poiByAccountId = new Map<Id, Park_Of_Interest__c>();
        Map<Id, Park_Of_Interest__c> poiByContactId = new Map<Id, Park_Of_Interest__c>();
        for (Park_Of_Interest__c newPOI : newPOIs) {
            if (newPOI.Account__c != null && newPOI.Contact__c == null) {
                poiByAccountId.put(newPOI.Account__c, newPOI);
            }

            if (newPOI.Account__c == null && newPOI.Contact__c != null) {
                poiByContactId.put(newPOI.Contact__c, newPOI);
            }
        }

        if (!poiByAccountId.isEmpty()) {
            ParkOfInterestTrigger_Helper.setMissingContactOnPOIs(poiByAccountId);
        }

        if (!poiByContactId.isEmpty()) {
            ParkOfInterestTrigger_Helper.addMissingAccountOnPOIs(poiByContactId);
        }
    }

    public static void onAfterInsert(Map<Id, Park_Of_Interest__c> newPOIMap) {
        if (avoidInsertRecursion) { return; }

        List<Park_Of_Interest__c> newPOIsNotCreatedFromSync = new List<Park_Of_Interest__c>();
        for (Park_Of_Interest__c poi : newPOIMap.values()) {
            //note: there are three possible outcomes from the condition below
            //  1) The POI is unique to the Contact, not created from the sync, and needs to be synced to related Contacts.
            //  2) The POI was already created from the sync, and be deleted as a duplicate.
            //  3) The POI is a duplicate, and be deleted as a duplicate.
            if (poi.Adventure_Park__c != null &&
                poi.Contact__c != null
            ) {
                newPOIsNotCreatedFromSync.add(poi);
            }
        }

        if (!newPOIsNotCreatedFromSync.isEmpty()) {
            ParkOfInterestTrigger_Helper.syncPOIsForContactsInRelatedAccount(newPOIsNotCreatedFromSync);
        }
    }

    public static void onBeforeUpdate(List<Park_Of_Interest__c> newPOIs, Map<Id, Park_Of_Interest__c> oldPOIMap) {

        Map<Id, Park_Of_Interest__c> poiByAccountId = new Map<Id, Park_Of_Interest__c>();
        for (Park_Of_Interest__c newPOI : newPOIs) {
            Park_Of_Interest__c oldPOI = oldPOIMap.get(newPOI.Id);

            if (newPOI.Account__c != oldPOI.Account__c) {
                if (newPOI.Account__c != null) {
                    poiByAccountId.put(newPOI.Account__c, newPOI);
                } else {
                    //@test: should_null_Contact_on_POI_when_Account_changes_to_null
                    newPOI.Contact__c = null;
                }
            }
        }

        if (!poiByAccountId.isEmpty()) {
            ParkOfInterestTrigger_Helper.setMissingContactOnPOIs(poiByAccountId);
        }
    }

    public static void onAfterDelete(List<Park_Of_Interest__c> deletedPOIs) {
        if (avoidDeleteRecursion) { return; }

        Map<String, Id> accountIdToParkId = new Map<String, Id>();
        List<String> parkContactCompositeKey = new List<String>();
        for (Park_Of_Interest__c poi : deletedPOIs) {
            if (poi.Contact__c != null && poi.Account__c != null) {
                accountIdToParkId.put(poi.Adventure_Park__c, poi.Account__c);
                parkContactCompositeKey.add(createCompositeKeyFromParkAndContact(poi));
            }
        }

        if (!accountIdToParkId.isEmpty()) {
            ParkOfInterestTrigger_Helper.cascadePOIDeleteToAccountContacts(accountIdToParkId, parkContactCompositeKey);
        }

        avoidDeleteRecursion = true;
    }

    public static String createCompositeKeyFromParkAndContact(Park_Of_Interest__c poi) {
        return poi.Adventure_Park__c + '-' + poi.Contact__c;
    }
}