force-app/main/default/objects/Adventure_Park__c/Adventure_Park__c.object-meta.xml
<CustomObject>
    <description>Represents one park where adventure is to be had!</description>
    <label>Adventure Park</label>
    <nameField>
        <label>Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure_Park__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Park_Of_Interest_Rating__c.field-meta.xml
<CustomField>
    <fullName>Park_Of_Interest_Rating__c</fullName>
    <description>Temporarily stores the rating for a given park, and nullified after the POI is created.</description>
    <label>Park Of Interest Rating</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Parks_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Parks_Of_Interest__c</fullName>
    <description>Some technology in our enterprise stack can update Lead records directly. During this update, this field is used to temporarily store Park Numbers, which are then used by the automation to create POIs.</description>
    <label>Parks Of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/Park_Of_Interest__c.object-meta.xml
<CustomObject>
    <description>A junction object between Lead/Contact and an Adventure Park. Allows one person to be interested in many adventure parks.</description>
    <label>Park Of Interest</label>
    <nameField>
        <displayFormat>POI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parks Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Of_Interest__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>Stores how much interest a person has in a particular park.</description>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/POICreatorForLeads.cls
public with sharing class POICreatorForLeads implements TriggerAction.AfterInsert, TriggerAction.AfterUpdate {

    public void afterInsert(List<Lead> newLeads) {
        List<Lead> leadsForParkOfInterest = new List<Lead>();
        for (Lead lead : newLeads) {

            if (lead.Parks_Of_Interest__c != null) {
                leadsForParkOfInterest.add(lead);
            }
        }

        if (!leadsForParkOfInterest.isEmpty()) {
            createParkOfInterestForNewLeads(leadsForParkOfInterest);
        }
    }

    //@test: should_create_POI_and_nullify_Lead()
    public static void createParkOfInterestForNewLeads(List<Lead> leads) {
        Map<Id, Adventure_Park__c> parksById = fetchLeadsInterestedAdventureParks(leads);

        List<Lead> leadsForUpdate = new List<Lead>();
        List<Park_Of_Interest__c> poiForInsert = new List<Park_Of_Interest__c>();
        for (Lead lead : leads) {
            Id parkId = Id.valueOf(lead.Parks_Of_Interest__c);

            if (parksById.containsKey(parkId) && parksById.get(parkId).Is_Active__c) {
                Park_Of_Interest__c poi = createPOI(parkId, lead);
                if (!poiForInsert.contains(poi)) {
                    poiForInsert.add(poi);
                }
            }

            Lead updatedLead = nullifyLeadPOIData(lead);
            leadsForUpdate.add(updatedLead);
        }
        if (!poiForInsert.isEmpty()) {
            insert poiForInsert;
        }

        if (!leadsForUpdate.isEmpty()) {
            update leadsForUpdate;
        }
    }

    private static Map<Id, Adventure_Park__c> fetchLeadsInterestedAdventureParks(List<Lead> leads) {
        Set<Id> parkIdsFromLeads = new Set<Id>();
        for (Lead lead : leads) {
            parkIdsFromLeads.add(Id.valueOf(lead.Parks_Of_Interest__c));
        }
        return new Map<Id, Adventure_Park__c>([SELECT Id, Is_Active__c FROM Adventure_Park__c WHERE Id IN :parkIdsFromLeads]);
    }

    private static Park_Of_Interest__c createPOI(Id parkId, Lead lead) {
        Park_Of_Interest__c poi = new Park_Of_Interest__c(
            Adventure_Park__c = parkId,
            Lead__c = lead.Id,
            Rating__c = lead.Park_Of_Interest_Rating__c
        );
        return poi;
    }

    private static Lead nullifyLeadPOIData(Lead lead) {
        Lead updatedLead = new Lead(
            Id = lead.Id,
            Parks_Of_Interest__c = null,
            Park_Of_Interest_Rating__c = null
        );
        return updatedLead;
    }

    public void afterUpdate(List<Lead> newLeads, List<SObject> triggerOld) {
        Set<Id> leadsForPark = new Set<Id>();
        for (Lead newLead : newLeads) {
            if (newLead.Parks_Of_Interest__c != null &&
                !newLead.IsConverted
            ) {
                leadsForPark.add(newLead.Id);
            }
        }

        if (!leadsForPark.isEmpty()) {
            createParkOfInterestForExistingLeads(leadsForPark);
        }
    }

    //@test: should_create_POI_for_existing_lead
    public static void createParkOfInterestForExistingLeads(Set<Id> leadIds) {
        List<Lead> leads = fetchLeadsWithPOIData(leadIds);
        Map<Id, Adventure_Park__c> parksById = fetchLeadsInterestedAdventureParks(leads);

        List<Lead> leadsForUpdate = new List<Lead>();
        List<Park_Of_Interest__c> poiForInsert = new List<Park_Of_Interest__c>();
        for (Lead lead : leads) {
            Set<Id> existingParkIds = new Set<Id>();
            for (Park_Of_Interest__c poi : lead.Parks_Of_Interest__r) {
                existingParkIds.add(poi.Adventure_Park__c);
            }

            Id parkId = Id.valueOf(lead.Parks_Of_Interest__c);
            Boolean hasList = existingParkIds.contains(parkId);
            Boolean validId = parksById.containsKey(parkId) && parksById.get(parkId).Is_Active__c;

            if (hasList == false && validId == true) {
                Park_Of_Interest__c poi = createPOI(parkId, lead);
                if (!poiForInsert.contains(poi)) {
                    poiForInsert.add(poi);
                }
            }

            Lead updatedLead = nullifyLeadPOIData(lead);
            leadsForUpdate.add(updatedLead);
        }
        if (!poiForInsert.isEmpty()) {
            insert poiForInsert;
        }

        if (!leadsForUpdate.isEmpty()) {
            update leadsForUpdate;
        }
    }

    private static List<Lead> fetchLeadsWithPOIData(Set<Id> leadIds) {
        List<Lead> leads = [
            SELECT Id, Parks_Of_Interest__c, Park_Of_Interest_Rating__c, Name, Email, (
                SELECT Id, Adventure_Park__c, Lead__c
                FROM Parks_Of_Interest__r
                WHERE Lead__c IN :leadIds
            )
            FROM Lead
            WHERE Id IN :leadIds
        ];
        return leads;
    }
}