force-app/main/default/objects/Adventure_Park__c/Adventure_Park__c.object-meta.xml
<CustomObject>
    <description>Represents one park where adventure is to be had!</description>
    <label>Adventure Park</label>
    <nameField>
        <label>Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure_Park__c/fields/Park_Number__c.field-meta.xml
<CustomField>
    <fullName>Park_Number__c</fullName>
    <description>The unique, 12 digit number assigned to a park.</description>
    <label>Park Number</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Adventure_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Timeframe__c</fullName>
    <description>The general timeframe for going on an adventure.</description>
    <label>Adventure Timeframe</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Household_Income__c.field-meta.xml
<CustomField>
    <fullName>Household_Income__c</fullName>
    <description>The general range of income for the lead.</description>
    <label>Household Income</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Most_Recent_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Lead_Source__c</fullName>
    <description>Leads come from many sources and will be updated to represent increased Lead engagement. This field shows the most recent touch point for the contact.</description>
    <label>Most Recent Lead Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Park_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Park_Of_Interest__c</fullName>
    <description>A temp field to write a POI Id to, which will be used to create a POI if not already existing.</description>
    <label>Park Of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Vendor_Segment_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Segment_Id__c</fullName>
    <description>The 3rd party partner Id where the contact originated from.</description>
    <label>Vendor Segment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Agent__c.field-meta.xml
<CustomField>
    <fullName>Is_Agent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the lead was created by an Agent on behalf of a Lead. This is necessary to know for commissions.</description>
    <label>Is Agent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Most_Recent_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Lead_Source__c</fullName>
    <description>Leads come from many sources and will be updated to represent increased Lead engagement. This field shows the most recent touch point for the lead.</description>
    <label>Most Recent Lead Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Parks_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Parks_Of_Interest__c</fullName>
    <description>Some technology in our enterprise stack can update Lead records directly. During this update, this field is used to temporarily store Park Numbers, which are then used by the automation to create POIs.</description>
    <label>Parks Of Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Vendor_Segment_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Segment_Id__c</fullName>
    <description>The 3rd party partner Id where the lead originated from.</description>
    <label>Vendor Segment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Park_Of_Interest__c/Park_Of_Interest__c.object-meta.xml
<CustomObject>
    <description>A junction object between Lead/Contact and an Adventure Park. Allows one person to be interested in many adventure parks.</description>
    <label>Park Of Interest</label>
    <nameField>
        <displayFormat>POI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parks Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Of_Interest__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/Temp_Lead__c.object-meta.xml
<CustomObject>
    <description>The basic information for a Lead coming from a variety of Lead Sources. Successfully mapped records can be safely deleted. By creating this temporary record, we can decouple the transformation logic and the integration logic.</description>
    <label>Temp Lead</label>
    <nameField>
        <displayFormat>TL-{000}</displayFormat>
        <label>Temp Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temp Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Temp_Lead__c/fields/Estimated_Household_Income__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Household_Income__c</fullName>
    <description>The general range of income for the lead/contact.</description>
    <label>Estimated Household Income</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Is_Agent__c.field-meta.xml
<CustomField>
    <fullName>Is_Agent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the temp lead was created by an Agent on behalf of a Lead. This is necessary to know for commissions.</description>
    <label>Is Agent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_Adventure_Date__c.field-meta.xml
<CustomField>
    <fullName>Lead_Adventure_Date__c</fullName>
    <description>The general/speculative date for the lead&apos;s adventure excursion.</description>
    <label>Lead Adventure Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_City__c.field-meta.xml
<CustomField>
    <fullName>Lead_City__c</fullName>
    <description>The city name of the lead&apos;s residence.</description>
    <label>Lead City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Lead_Country_Code__c</fullName>
    <description>A two or three letter country code representing the Lead&apos;s country location.</description>
    <label>Lead Country Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_Email__c.field-meta.xml
<CustomField>
    <fullName>Lead_Email__c</fullName>
    <label>Lead Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_First_Name__c</fullName>
    <label>Lead First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Last_Name__c</fullName>
    <label>Lead Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Phone_Number__c</fullName>
    <label>Lead Phone Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Lead_Postal_Code__c</fullName>
    <description>The postal code of the Lead&apos;s residence.</description>
    <label>Lead Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>As leads can come from many marketing channels, this helps with attribution.</description>
    <label>Lead Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_State__c.field-meta.xml
<CustomField>
    <fullName>Lead_State__c</fullName>
    <description>The two digit state code for US based addresses.</description>
    <label>Lead State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Lead_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Lead_Street_Address__c</fullName>
    <description>The street number and street name for the lead.</description>
    <label>Lead Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Park_Number__c.field-meta.xml
<CustomField>
    <fullName>Park_Number__c</fullName>
    <description>The park number of the park the lead or contact is interested in. Used to easily match the correct Adventure Park record.</description>
    <label>Park Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, this represents a successfully processed record and can be safely deleted. Successful processing can result in an existing Lead or Contact being updated, a new Lead created, or a Lead being automatically converted.</description>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Temp_Lead__c/fields/Vendor_Segment_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Segment_Id__c</fullName>
    <description>Some temp leads come from 3rd party partners. The term used by the marketing team is Vendor Segment. This represents that relationship.</description>
    <label>Vendor Segment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/temp-lead/TempLeadTrigger_Handler.cls
public with sharing class TempLeadTrigger_Handler {

    private static final Map<String, Temp_Lead__c> tempLeadByEmail = new Map<String, Temp_Lead__c>();
    private static final Map<String, Temp_Lead__c> tempLeadByPhone = new Map<String, Temp_Lead__c>();
    private static final List<String> tempParkNumbers = new List<String>();

    public static void onAfterInsert(Map<Id, Temp_Lead__c> tempLeadsById) {
        collectEmailsPhonesAndParkNumbers(tempLeadsById);
        Map<String, Id> parkIdByParkName = getParkIdByParkName(tempParkNumbers);
        List<Temp_Lead__c> processedTempLeads = new List<Temp_Lead__c>();

        processedTempLeads.addAll(
            handleTempLeadMatchingContact(tempLeadsById, parkIdByParkName)
        );

        if (!tempLeadsById.isEmpty()) {
            processedTempLeads.addAll(
                handleTempLeadMatchingLead(tempLeadsById, parkIdByParkName)
            );
        }

        if (!processedTempLeads.isEmpty()) {
            update processedTempLeads;
        }
    }

    private static void collectEmailsPhonesAndParkNumbers(Map<Id, Temp_Lead__c> tempLeadsById) {
        for (Temp_Lead__c tempLead : tempLeadsById.values()) {
            if (String.isNotBlank(tempLead.Lead_Email__c)) {
                tempLeadByEmail.put(tempLead.Lead_Email__c, tempLead);
            }

            if (String.isNotBlank(tempLead.Lead_Phone_Number__c)) {
                tempLeadByPhone.put(tempLead.Lead_Phone_Number__c, tempLead);
            }

            if (String.isNotBlank(tempLead.Park_Number__c)) {
                tempParkNumbers.add(tempLead.Park_Number__c);
            }
        }
    }

    private static Map<String, Id> getParkIdByParkName(List<String> parkNumbers) {
        Map<String, Id> parkIdByParkName = new Map<String, Id>();
        for (Adventure_Park__c park: [SELECT Id, Park_Number__c FROM Adventure_Park__c WHERE Park_Number__c IN :parkNumbers]) {
            parkIdByParkName.put(park.Park_Number__c, park.Id);
        }
        return parkIdByParkName;
    }

    private static List<Temp_Lead__c> handleTempLeadMatchingContact(Map<Id, Temp_Lead__c> tempLeadsById, Map<String, Id> parkIdByParkName) {
        List<Contact> existingContacts = new List<Contact>();
        List<Contact> newContacts = new List<Contact>();
        List<Temp_Lead__c> processedTempLeads = new List<Temp_Lead__c>();
        for (Contact contact: findForExistingContacts(tempLeadByEmail.keySet(), tempLeadByPhone.keySet())) {
            Temp_Lead__c tempLead = tempLeadByEmail.get(contact.Email);
            if (tempLead == null) {
                tempLead = tempLeadByPhone.get(contact.Phone);
            }
            if (tempLead == null) { continue; }

            if (tempLead.Lead_First_Name__c == contact.FirstName &&
                tempLead.Lead_Last_Name__c == contact.LastName
            ) {
                contact.Park_Of_Interest__c = parkIdByParkName.get(tempLead.Park_Number__c);
                existingContacts.add(contact);
            }
            else {
                Contact relatedContact = createRelatedContactFromTempLead(tempLead, contact);
                relatedContact.Park_Of_Interest__c = parkIdByParkName.get(tempLead.Park_Number__c);
                newContacts.add(relatedContact);
            }

            tempLeadByEmail.remove(tempLead.Lead_Email__c);
            tempLeadByPhone.remove(tempLead.Lead_Phone_Number__c);
            tempLeadsById.remove(tempLead.Id);
            processedTempLeads.add(new Temp_Lead__c(
                Id = tempLead.Id,
                Processed__c = true
            ));
        }

        if (!existingContacts.isEmpty()) {
            update existingContacts;
        }

        if (!newContacts.isEmpty()) {
            insert newContacts;
        }

        return processedTempLeads;
    }

    private static List<Contact> findForExistingContacts(Set<String> tempEmails, Set<String> tempPhones) {
        return [
            SELECT FirstName, LastName, Email, Phone, Park_Of_Interest__c
            FROM Contact
            WHERE Email IN :tempEmails
            OR Phone IN :tempPhones
            FOR UPDATE
        ];
    }

    private static Contact createRelatedContactFromTempLead(Temp_Lead__c tempLead, Contact contact) {
        /**
        * - true creates a full copy, all fields are duplicated in memory, including relationship fields. Consequently,
        *   if you change a field on the cloned SObject, the original SObject isn’t affected.
        * - false performs a shallow copy, all copied relationship fields reference the original. Consequently,
        *   if you change a relationship field, the corresponding field on the original is also affected, & vice versa.
        */
        Contact relatedContact = contact.clone(false, true);
        relatedContact.FirstName = tempLead.Lead_First_Name__c;
        relatedContact.LastName = tempLead.Lead_Last_Name__c;
        return relatedContact;
    }

    private static List<Temp_Lead__c> handleTempLeadMatchingLead(Map<Id, Temp_Lead__c> tempLeadsById, Map<String, Id> parkIdByParkName) {
        List<Lead> existingLeads = findExistingLeads(tempLeadByEmail.keySet(), tempLeadByPhone.keySet());

        List<Lead> newLeads = new List<Lead>();
        List<Lead> updatedLeads = new List<Lead>();
        List<Temp_Lead__c> processedTempLeads = new List<Temp_Lead__c>();
        if (existingLeads.isEmpty()) {
            for (Temp_Lead__c tempLead: tempLeadsById.values()) {
                newLeads.add(
                    createLeadFromTemp(tempLead)
                );

                processedTempLeads.add(new Temp_Lead__c(
                    Id = tempLead.Id,
                    Processed__c = true
                ));
            }
        } else {
            for (Lead lead: existingLeads) {
                Temp_Lead__c tempLead = tempLeadByEmail.get(lead.Email);
                if (tempLead == null) {
                    tempLead = tempLeadByPhone.get(lead.Phone);
                }

                if (tempLead == null) {
                    continue;
                }
                else if (tempLead.Lead_First_Name__c != lead.FirstName ||
                    tempLead.Lead_Last_Name__c != lead.LastName
                ) {
                    newLeads.add(createLeadFromTemp(tempLead));
                }
                else {
                    lead.Parks_Of_Interest__c = parkIdByParkName.get(tempLead.Park_Number__c);
                    updatedLeads.add(lead);
                }

                tempLeadByEmail.remove(tempLead.Lead_Email__c);
                tempLeadByPhone.remove(tempLead.Lead_Phone_Number__c);
                processedTempLeads.add(new Temp_Lead__c(
                    Id = tempLead.Id,
                    Processed__c = true
                ));
            }
        }

        if (!updatedLeads.isEmpty()) {
            update updatedLeads;
        }

        if (!newLeads.isEmpty()) {
            insert newLeads;
        }

        return processedTempLeads;
    }

    private static List<Lead> findExistingLeads(Set<String> tempEmails, Set<String> tempPhones) {
        return [
            SELECT FirstName, LastName, Email, Phone, Parks_Of_Interest__c
            FROM Lead
            WHERE Email IN :tempEmails
            OR Phone IN :tempPhones
            FOR UPDATE
        ];
    }

    private static Lead createLeadFromTemp(Temp_Lead__c tempLead) {
        return new Lead(
            FirstName = tempLead.Lead_First_Name__c,
            LastName = tempLead.Lead_Last_Name__c,
            Email = tempLead.Lead_Email__c,
            Phone = tempLead.Lead_Phone_Number__c,
            Vendor_Segment_Id__c = tempLead.Vendor_Segment_Id__c,
            Company = tempLead.Lead_Last_Name__c,
            Country = tempLead.Lead_Country_Code__c,
            State = tempLead.Lead_State__c,
            Street = tempLead.Lead_Street_Address__c,
            City = tempLead.Lead_City__c,
            PostalCode = tempLead.Lead_Postal_Code__c,
            Is_Agent__c = tempLead.Is_Agent__c,
            Household_Income__c = estimatedHouseHoldIncome(tempLead.Estimated_Household_Income__c),
            Adventure_Timeframe__c = adventureTimeFrame(tempLead.Lead_Adventure_Date__c),
            Most_Recent_Lead_Source__c = tempLead.Lead_Source__c
        );
    }

    @TestVisible
    private static String estimatedHouseHoldIncome(String inputIncome) {
        if (String.isBlank(inputIncome)) { return 'Under $64K';  }

        inputIncome = inputIncome.replace('$', '').replace(',', '').trim();
        if (inputIncome.split('-').size() == 1) {
            inputIncome = inputIncome.replace('+', '');
        } else {
            inputIncome = inputIncome.split('-').get(1);
        }

        Integer income;
        try {
            income = Integer.valueOf(inputIncome.trim());
        } catch (TypeException typeException) {
            return 'Under $64K';
        }

        if (income == null || income < 65000) { inputIncome = 'Under $64K'; }
        else if (income <= 99999) { inputIncome = '$65K-99K'; }
        else if (income <= 149999) { inputIncome = '$100K-149K'; }
        else if (income <= 199999) { inputIncome = '$150K-199K'; }
        else if (income <= 249999) { inputIncome = '$200K-249K'; }
        else if (income <= 299999) { inputIncome = '$250K-299K'; }
        else { inputIncome = '$300K+'; }

        return inputIncome;
    }

    @TestVisible
    private static String adventureTimeFrame(String inputTimeFrame) {
        if (inputTimeFrame == null) { return  null; }

        String[] dateParts = inputTimeFrame.trim().split('/');
        Integer year = Integer.valueOf(dateParts[1].trim());
        Integer month = Integer.valueOf(dateParts[0].trim());

        Date moveInDate = Date.newInstance(year, month, 01);
        Date today = Date.today();
        Integer monthDiff = today.monthsBetween(moveInDate);

        //Instructed to round down the month difference.
        if (monthDiff <= 2) { inputTimeFrame = '1 Month'; }
        else if (monthDiff <= 5) { inputTimeFrame = '3 Months'; }
        else if (monthDiff <= 8) { inputTimeFrame = '6 Months'; }
        else if (monthDiff <= 11) { inputTimeFrame = '9 Months'; }
        else { inputTimeFrame = '1 Year +'; }

        return inputTimeFrame;
    }
}