force-app/main/default/objects/Adventure_Park__c/Adventure_Park__c.object-meta.xml
<CustomObject>
    <description>Represents one park where adventure is to be had!</description>
    <label>Adventure Park</label>
    <nameField>
        <label>Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Tour__c/Park_Tour__c.object-meta.xml
<CustomObject>
    <description>A junction object between Leads/Contact and Adventure Parks. Represents an actual tour of a park, which differentiates itself from POIs. Parks of Interest represents merely interest and desired park adventure. But a Park Tour is an actual tour of the adventure.</description>
    <label>Park Tour</label>
    <nameField>
        <displayFormat>PT-{000}</displayFormat>
        <label>Park Tour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Park Tour</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Tour__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Return_Visitor__c.field-meta.xml
<CustomField>
    <fullName>Return_Visitor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return Visitor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ParkTourTrigger_Helper.cls
public without sharing class ParkTourTrigger_Helper {

    //@test: should_mark_second_Park_Tour_for_Lead_as_Return_Visitor
    //@test: should_handle_Lead_mixed_scenario_Park_Tour_insert
    public static void checkLeadForRepeatTour(List<Park_Tour__c> newTours, List<Id> leadIds) {
        Map<Id, Lead> leadById = new Map<Id, Lead>([
            SELECT Id,
            (SELECT Id, Adventure_Park__c FROM Park_Tour__r)
            FROM Lead
            WHERE Id IN :leadIds
        ]);

        for (Park_Tour__c tour : newTours) {
            Lead lead = leadById.get(tour.Lead__c);
            if (lead == null || lead.Park_Tour__r.size() == 0) { continue; }

            for (Park_Tour__c existingTour : lead.Park_Tour__r) {
                if (existingTour.Adventure_Park__c == tour.Adventure_Park__c) {
                    tour.Return_Visitor__c = true;
                    break;
                }
            }
        }
    }

    //@test: should_mark_second_Park_Tour_for_Contact_as_Return_Visitor
    //@test: should_handle_Contact_mixed_scenario_Park_Tour_insert
    public static void checkContactForRepeatTour(List<Park_Tour__c> newTours, List<Id> contactIds) {
        Map<Id, Contact> contactById = new Map<Id, Contact>([
            SELECT AccountId,
            (SELECT Adventure_Park__c FROM Park_Tour__r WHERE Adventure_Park__c != NULL)
            FROM Contact
            WHERE Id IN :contactIds
        ]);

        for (Park_Tour__c tour : newTours) {
            Contact contact = contactById.get(tour.Contact__c);
            if (contact == null || contact.Park_Tour__r.size() == 0) { continue; }

            if (contact.AccountId != null) {
                tour.Account__c = contact.AccountId;
            }

            for (Park_Tour__c existingTour : contact.Park_Tour__r) {
                if (existingTour.Adventure_Park__c == tour.Adventure_Park__c) {
                    tour.Return_Visitor__c = true;
                    break;
                }
            }
        }
    }
}